//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationB.ServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IJobDitributer")]
    public interface IJobDitributer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobDitributer/Connect", ReplyAction="http://tempuri.org/IJobDitributer/ConnectResponse")]
        bool Connect(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobDitributer/Connect", ReplyAction="http://tempuri.org/IJobDitributer/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync(string type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobDitributerChannel : ApplicationB.ServerService.IJobDitributer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobDitributerClient : System.ServiceModel.ClientBase<ApplicationB.ServerService.IJobDitributer>, ApplicationB.ServerService.IJobDitributer {
        
        public JobDitributerClient() {
        }
        
        public JobDitributerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobDitributerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobDitributerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobDitributerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Connect(string type) {
            return base.Channel.Connect(type);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync(string type) {
            return base.Channel.ConnectAsync(type);
        }
    }
}
