//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationA.ClientService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.IJobPerformer")]
    public interface IJobPerformer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPerformer/IsLive", ReplyAction="http://tempuri.org/IJobPerformer/IsLiveResponse")]
        bool IsLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPerformer/IsLive", ReplyAction="http://tempuri.org/IJobPerformer/IsLiveResponse")]
        System.Threading.Tasks.Task<bool> IsLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPerformer/DoWork", ReplyAction="http://tempuri.org/IJobPerformer/DoWorkResponse")]
        bool DoWork(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPerformer/DoWork", ReplyAction="http://tempuri.org/IJobPerformer/DoWorkResponse")]
        System.Threading.Tasks.Task<bool> DoWorkAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobPerformerChannel : ApplicationA.ClientService.IJobPerformer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobPerformerClient : System.ServiceModel.ClientBase<ApplicationA.ClientService.IJobPerformer>, ApplicationA.ClientService.IJobPerformer {
        
        public JobPerformerClient() {
        }
        
        public JobPerformerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobPerformerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobPerformerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobPerformerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsLive() {
            return base.Channel.IsLive();
        }
        
        public System.Threading.Tasks.Task<bool> IsLiveAsync() {
            return base.Channel.IsLiveAsync();
        }
        
        public bool DoWork(string value) {
            return base.Channel.DoWork(value);
        }
        
        public System.Threading.Tasks.Task<bool> DoWorkAsync(string value) {
            return base.Channel.DoWorkAsync(value);
        }
    }
}
